
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[491] =
    {   0,
       74,   74,   83,   82,   75,   74,   82,   81,   82,   72,
       72,   82,   78,   72,   72,   72,   72,   72,   79,   72,
       72,   72,   82,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   82,   75,   75,   74,   72,    0,
       80,   81,   71,   71,   71,   71,   71,   72,    0,   80,
       73,    0,   81,   79,   18,   17,   79,   79,    0,   72,
        2,   81,   81,   81,   22,   81,   81,   81,   81,   81,
       81,   77,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   76,   81,   81,   81,   81,   81,

       72,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   80,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,    0,   79,   79,
       18,   18,   18,   18,   17,    0,   81,   20,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   31,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   76,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   54,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       66,   81,   68,   69,   81,   81,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   79,   18,   18,

       18,    0,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   32,   33,   81,   81,   81,   81,
       81,   81,   41,   42,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   53,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   79,   81,   81,
       81,   15,   16,   71,    0,   71,   71,    9,   71,    5,
       71,   71,   71,   71,   71,   18,    1,   81,   21,   81,
       24,   25,   26,   27,   81,   81,   81,   81,   81,   81,
       34,   81,   81,   38,   81,   81,   81,   44,   81,   81,
       81,   81,   81,   81,   81,   81,   52,   81,   56,   81,

       81,   81,   81,   81,   81,   81,   64,   65,   67,   70,
        0,   71,    0,   71,   71,   71,   71,    6,   71,   71,
       71,   81,   81,   81,   81,   81,   30,   81,   81,   36,
       81,   81,   81,   81,   81,   81,   47,   81,   81,   81,
       81,   81,   81,   81,   81,   59,   81,   62,   63,    0,
       71,    0,   71,   71,    7,   71,   71,   71,   71,   81,
       81,   81,   28,   29,   81,   81,   81,   81,   43,   45,
       81,   81,   77,   81,   81,   81,   81,   57,   81,   60,
        0,    0,   71,   71,    0,   71,   11,   71,   71,    4,
       71,   19,   23,   81,   81,   81,   40,   46,   81,   81,

       81,   81,   81,   81,   81,   81,    0,    0,   71,   71,
        0,   71,    3,    8,   10,   81,   81,   39,   81,   81,
       81,   50,   51,   81,   58,   81,    0,    0,   71,   71,
        0,   71,   35,   37,   48,   81,   49,   81,   81,    0,
        0,   71,   71,    0,   71,   81,   55,   81,    0,    0,
       71,   71,    0,   71,   61,    0,    0,   71,   71,   13,
       13,    0,    0,   71,   71,    0,    0,   71,   71,    0,
        0,   71,   71,    0,    0,   71,   71,    0,    0,   71,
       71,   12,    0,   12,   71,    0,   71,   14,   14,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   33,
        2,    1,   49,    1,   50,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   33,   51,   52,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    1,    1,
        3,    1,    1,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    6,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[500] =
    {   0,
        0,    0,  948,  949,   52,   54,  926,  103,   34,  949,
      938,  936,  949,  923,   46,   45,   50,   57,   54,   41,
      922,  921,  919,   55,   58,  136,   62,  140,  146,   60,
      919,  144,   56,   61,   65,  138,  167,  151,  162,  168,
      175,  137,   64,  170,  887,  160,  889,  198,  916,  931,
        0,    0,  894,    0,  891,  902,  178,  949,  923,  922,
      949,  198,  909,  194,  210,    0,  200,  207,  890,  907,
      949,  203,   66,  208,  906,  206,  209,  212,  211,  214,
      210,  905,  225,  216,  218,  171,  238,  221,  220,  233,
      239,  240,  244,  242,  904,  245,  246,  248,  250,  247,

      903,  252,  262,  253,  255,  275,  254,  260,  281,  266,
      276,  282,  285,  286,  288,  918,    0,  892,  878,  881,
      881,  881,  885,  283,  878,  887,  886,  898,  894,  294,
      310,  312,  318,  328,    0,  880,  293,  889,  311,  317,
      298,  318,  316,  322,  324,  326,  327,  328,  888,  329,
      330,  332,  344,  335,  334,  338,  336,  358,  353,  359,
      362,  351,  363,  367,  370,  371,  372,  373,  887,  390,
      375,  376,  380,  382,  383,  385,  386,  384,  389,  396,
      886,  397,  885,  884,  388,  409,  388,  865,  358,  865,
      857,  866,  857,  861,  856,  857,  390,  878,  431,  883,

      433,  855,  414,  416,  417,  418,  425,  420,  429,  427,
      431,  437,  432,  438,  872,  460,  439,  445,  433,  448,
      447,  451,  871,  870,  446,  457,  453,  465,  458,  470,
      469,  459,  474,  463,  475,  869,  478,  479,  484,  485,
      488,  493,  486,  494,  490,  491,  496,  868,  498,  500,
      503,    0,    0,  524,  860,  859,  852,    0,  857,    0,
      859,  840,  838,  836,  838,  867,  949,  510,  857,  511,
      856,  855,  854,  853,  512,  514,  517,  519,  521,  522,
      852,  524,  523,  851,  525,  527,  533,  535,  537,  540,
      541,  544,  546,  545,  547,  548,  850,  557,  849,  554,

      558,  560,  562,  567,  566,  568,  848,  847,  846,  845,
      824,  823,  822,  821,  829,  818,  835,    0,  830,  829,
      824,  569,  570,  572,  573,  575,  834,  577,  579,  581,
      586,  587,  589,  590,  592,  594,  833,  591,  596,  599,
      600,  609,  605,  607,  613,  832,  615,  831,  830,  613,
      616,  809,  808,  820,    0,  812,  804,  804,  806,  618,
      621,  624,  822,  821,  626,  627,  632,  634,  820,  819,
      633,  636,  654,  639,  642,  643,  644,  818,  650,  645,
      792,  795,  790,  793,  796,  795,    0,  790,  788,    0,
      793,  808,  807,  647,  651,  653,  806,  805,  655,  658,

      661,  660,  662,  670,  666,  671,  680,  786,  689,  785,
      782,  781,    0,    0,    0,  679,  680,  800,  676,  682,
      684,  799,  798,  685,  797,  687,  778,  778,  776,  776,
      775,  761,  762,  752,  748,  689,  747,  691,  695,  729,
      729,  727,  727,  721,  719,  699,  739,  701,  716,  715,
      714,  713,  724,  723,  731,  708,  722,  706,  720,  949,
        0,  709,  712,  720,  721,  720,  715,  718,  713,  719,
      714,  717,  712,  695,  713,  693,  711,  710,  706,  708,
      704,  949,  326,    0,  292,  238,  123,  949,    0,  949,
       85,  771,  775,  781,  783,  789,  795,  801,  807

    } ;

static yyconst flex_int16_t yy_def[500] =
    {   0,
      490,    1,  490,  490,  490,  490,  490,  490,  491,  490,
      490,  492,  490,  490,  490,  490,  493,  490,  493,  490,
      490,  490,  490,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  490,  490,  490,  490,  490,  494,
        8,    8,  495,  495,  495,  495,  495,  490,  492,  492,
      490,  490,  493,  493,  496,  497,  493,  493,  490,  490,
      490,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,

      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  494,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  490,  490,  490,
      496,  496,  496,  498,  497,  490,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  495,  495,  490,  498,  499,

      498,  490,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  495,  495,  495,  490,  495,  495,  495,  495,  495,
      495,  495,  495,  495,  495,  499,  490,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,

      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      490,  495,  490,  495,  495,  495,  495,  495,  495,  495,
      495,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  490,
      495,  490,  495,  495,  495,  495,  495,  495,  495,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      490,  490,  495,  495,  490,  495,  495,  495,  495,  495,
      495,  493,  493,  493,  493,  493,  493,  493,  493,  493,

      493,  493,  493,  493,  493,  493,  490,  490,  495,  495,
      490,  495,  495,  495,  495,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  490,  490,  495,  495,
      490,  495,  493,  493,  493,  493,  493,  493,  493,  490,
      490,  495,  495,  490,  495,  493,  493,  493,  490,  490,
      495,  495,  490,  495,  493,  490,  490,  495,  495,  490,
      495,  490,  490,  495,  495,  490,  490,  495,  495,  490,
      490,  495,  495,  490,  490,  495,  495,  490,  490,  495,
      495,  490,  490,  495,  495,  490,  495,  490,  495,    0,
      490,  490,  490,  490,  490,  490,  490,  490,  490

    } ;

static yyconst flex_uint16_t yy_nxt[1003] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   14,   15,   13,   16,   17,   18,   19,   13,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   31,   31,   33,   31,   34,   35,   36,   31,
       37,   38,   39,   40,   41,   42,   43,   44,    4,   31,
       13,   45,   13,   46,   46,   46,   48,   53,   61,   61,
       62,   58,   58,   69,   55,   58,   58,   64,   65,   67,
       58,   68,   56,   66,  490,  490,  490,   58,  490,   72,
      490,  490,  490,   57,  490,  490,  490,   99,  100,   80,
       54,   73,  138,   81,   93,   74,   75,   94,   76,   82,

       47,  114,   47,   50,   50,  101,   50,   51,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   52,   50,
       52,   50,   50,   50,   50,   50,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   50,   52,   50,   50,   50,  490,  490,  490,   77,
      490,   46,   46,  489,  490,   83,  490,  113,  102,   89,
       78,  490,   95,   79,   84,   85,   86,   90,  103,   96,
       97,  104,  490,   91,   87,   98,   88,  490,  490,   92,
      490,  490,  108,  106,  105,  490,  107,  153,  112,   46,

       48,  115,  109,  121,  110,  122,  123,  124,   47,  111,
      128,   64,  132,  129,  490,  130,  125,   64,  126,  127,
      490,  133,   67,  490,   68,  134,  490,  490,  490,  490,
      490,  490,  490,  140,  490,  144,  490,  149,  490,  147,
      490,  490,  148,  141,  137,  490,   47,  146,  139,  145,
      142,  143,  155,  490,  157,  150,  152,  151,  490,  490,
      490,  154,  490,  156,  490,  490,  490,  490,  490,  158,
      490,  164,  490,  490,  490,  490,  160,  173,  488,  159,
      490,  161,  490,  163,  162,  177,  490,  165,  166,  167,
      170,  168,  169,  171,  174,  490,  490,  175,  176,  172,

      178,  490,  490,  183,  179,  490,  490,  182,  490,  129,
      193,  130,  132,  490,  132,  186,  185,  194,  490,  487,
      132,  133,  184,  133,  180,  134,  101,  134,  181,  133,
      200,  490,  206,  134,  204,  203,  490,  490,  490,  201,
      205,  207,  490,  134,  490,   82,  490,  490,  490,  490,
      490,  213,  490,  486,  490,  490,  490,  216,  490,  214,
      209,  212,  255,  208,  490,  225,  215,  210,  211,  223,
      218,  490,  219,  490,  217,  220,  224,  226,  490,  490,
      228,  227,  490,  490,  229,  221,  230,  490,   82,  222,
      490,  490,  490,  490,  237,  490,  490,  231,  234,  235,

      490,  232,  490,  490,  490,  490,  490,  256,  490,  490,
      490,  238,  233,  252,  241,  236,  490,  490,  240,  239,
      247,  246,  250,  248,  249,  242,  243,  244,  245,  490,
      264,  265,  253,  200,  490,  200,  490,  490,  490,  237,
      490,  270,  201,  251,  201,  490,  134,  490,  134,  490,
       82,  490,  490,  490,  268,  271,  273,  490,  490,  490,
      276,  272,  275,  269,  279,  490,  490,  490,  490,  274,
      283,  490,  282,  490,  278,  277,  284,  490,  490,  490,
      490,  286,  287,  490,  248,  490,  281,  288,  289,  490,
      490,  280,  285,  291,  490,  490,  292,  294,  490,  490,

      290,  295,  293,  296,  490,  490,  490,  300,  490,  279,
      490,  490,  301,  490,  490,  306,  490,  297,  490,  302,
      490,  299,  298,  490,  303,  305,  304,   95,  311,  310,
      490,  490,  490,  322,  490,  323,  307,  490,  308,  490,
      309,  490,  490,  490,  490,  490,  327,  490,  324,  329,
       95,  326,  328,  490,  325,  490,  331,  490,  332,  333,
      490,  490,  335,  330,  490,  490,  490,  490,  490,  334,
      341,  336,  339,  312,  490,  337,  342,  490,  490,  338,
      490,  340,  490,  345,  343,  346,  490,  490,  490,  490,
      490,  348,  490,  490,  360,  490,  344,  490,  349,  490,

      363,  490,  347,   82,  361,   95,  490,  490,  366,  490,
      490,  490,  490,  365,  490,  362,  490,  364,  372,  490,
      490,  368,   95,  373,  374,  490,  375,  490,  367,  490,
      369,  371,  376,  490,  378,  490,  381,  370,  490,  383,
      382,  490,  380,  384,  490,  377,  490,  490,  393,  394,
      395,   82,  490,  490,  490,  379,  490,  396,  400,  490,
      392,  397,  490,  490,  490,  490,  401,  490,  403,  398,
      490,  490,  399,  490,  490,  490,  417,  405,  490,  402,
      490,  490,  490,  418,  427,  404,  490,  416,  422,  423,
      490,  490,  425,  427,  406,  420,  490,  419,  421,  490,

      490,  424,  490,  400,  490,  490,  433,  490,  426,  490,
      434,  490,  437,  466,  446,  490,  467,  435,  436,  490,
      448,  490,  438,  439,  466,  467,   82,  447,  455,  427,
      485,  484,  483,  482,  481,  480,  479,  478,  429,  477,
      476,  475,  474,  473,  472,  471,  470,  465,  464,  463,
      462,  490,  461,  460,  459,  458,  457,  456,  466,  490,
      454,  467,  453,  452,  451,  450,  449,  490,  490,  468,
      469,   59,  490,   59,   59,   59,   59,   63,   63,   63,
       63,   50,  490,   50,   50,   50,   50,  117,  117,  131,
      131,  131,  131,  131,  131,  135,  445,  135,  135,  135,

      135,  199,  199,  199,  199,  199,  199,  200,  200,  200,
      444,  200,  200,  443,  442,  441,  440,  490,  490,  490,
      490,  432,  431,  430,  428,  490,  490,  490,  490,  415,
      414,  413,  412,  411,  410,  409,  408,  407,  490,  490,
      490,  490,  490,  391,  390,  389,  388,  387,  386,  385,
      490,  490,  490,  490,  490,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  266,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  490,  490,
      490,  490,  490,  267,  266,  198,  263,  262,  261,  260,

      259,  258,  257,  254,  490,  490,  490,  490,  490,  490,
      202,  198,   62,  197,  196,  195,  192,  191,  190,  189,
      188,  187,  116,  490,  490,  490,  490,   58,  136,  490,
       60,   60,  120,  119,  118,  116,   58,   47,   58,  490,
       71,   58,   70,   58,   60,   58,   49,  490,    3,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490
    } ;

static yyconst flex_int16_t yy_chk[1003] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    6,    6,    9,   15,   16,
       15,   20,   20,   20,    9,   16,   15,   17,   18,   19,
       17,   19,    9,   18,   19,   24,   33,   18,   25,   24,
       30,   34,   27,    9,   43,   35,   73,   33,   34,   27,
      491,   24,   73,   27,   30,   24,   24,   30,   25,   27,

        5,   43,    6,    8,    8,   35,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   26,   42,   36,   26,
       28,   46,   46,  487,   32,   28,   29,   42,   36,   29,
       26,   38,   32,   26,   28,   28,   28,   29,   36,   32,
       32,   36,   39,   29,   28,   32,   28,   37,   40,   29,
       44,   86,   39,   38,   37,   41,   38,   86,   41,   48,

       48,   44,   39,   57,   40,   57,   57,   57,   46,   40,
       62,   64,   65,   62,   64,   62,   57,   67,   57,   57,
       67,   65,   68,   72,   68,   65,   76,   68,   74,   77,
       81,   79,   78,   76,   80,   78,   84,   81,   85,   80,
       89,   88,   80,   77,   72,   83,   48,   79,   74,   78,
       77,   77,   88,   90,   89,   83,   85,   84,   87,   91,
       92,   87,   94,   88,   93,   96,   97,  100,   98,   90,
       99,   97,  102,  104,  107,  105,   92,  104,  486,   91,
      108,   93,  103,   96,   94,  107,  110,   97,   97,   98,
      102,   99,  100,  103,  105,  106,  111,  105,  106,  103,

      108,  109,  112,  111,  109,  113,  114,  110,  115,  130,
      124,  130,  131,  137,  132,  115,  113,  124,  141,  485,
      133,  131,  112,  132,  109,  131,  114,  132,  109,  133,
      134,  139,  141,  133,  139,  137,  143,  140,  142,  134,
      140,  143,  144,  134,  145,  142,  146,  147,  148,  150,
      151,  148,  152,  483,  155,  154,  157,  151,  156,  148,
      145,  147,  189,  144,  153,  156,  150,  146,  146,  154,
      153,  162,  153,  159,  152,  153,  155,  157,  158,  160,
      159,  158,  161,  163,  160,  153,  161,  164,  162,  153,
      165,  166,  167,  168,  170,  171,  172,  163,  166,  167,

      173,  164,  174,  175,  178,  176,  177,  189,  185,  179,
      170,  171,  165,  187,  173,  168,  180,  182,  172,  171,
      179,  178,  185,  180,  182,  174,  175,  176,  177,  186,
      197,  197,  187,  199,  203,  201,  204,  205,  206,  170,
      208,  206,  199,  186,  201,  207,  199,  210,  201,  209,
      205,  211,  213,  219,  203,  207,  209,  212,  214,  217,
      212,  208,  211,  204,  216,  218,  225,  221,  220,  210,
      219,  222,  218,  227,  214,  213,  220,  226,  229,  232,
      216,  222,  225,  234,  226,  228,  217,  227,  228,  231,
      230,  216,  221,  230,  233,  235,  231,  233,  237,  238,

      229,  233,  232,  234,  239,  240,  243,  239,  241,  216,
      245,  246,  240,  242,  244,  245,  247,  235,  249,  241,
      250,  238,  237,  251,  242,  244,  243,  250,  254,  251,
      268,  270,  275,  268,  276,  270,  246,  277,  247,  278,
      249,  279,  280,  283,  282,  285,  278,  286,  275,  282,
      280,  277,  279,  287,  276,  288,  285,  289,  286,  287,
      290,  291,  289,  283,  292,  294,  293,  295,  296,  288,
      295,  290,  293,  254,  300,  291,  296,  298,  301,  292,
      302,  294,  303,  301,  298,  302,  305,  304,  306,  322,
      323,  305,  324,  325,  322,  326,  300,  328,  306,  329,

      325,  330,  303,  304,  323,  328,  331,  332,  330,  333,
      334,  338,  335,  329,  336,  324,  339,  326,  338,  340,
      341,  332,  335,  339,  340,  343,  341,  344,  331,  342,
      333,  336,  342,  345,  344,  347,  350,  334,  360,  351,
      350,  361,  347,  351,  362,  343,  365,  366,  361,  365,
      366,  362,  367,  371,  368,  345,  372,  367,  373,  374,
      360,  368,  375,  376,  377,  380,  374,  394,  376,  371,
      379,  395,  372,  396,  373,  399,  395,  379,  400,  375,
      402,  401,  403,  396,  407,  377,  405,  394,  402,  403,
      404,  406,  405,  409,  380,  400,  419,  399,  401,  416,

      417,  404,  420,  373,  421,  424,  416,  426,  406,  436,
      417,  438,  421,  462,  436,  439,  463,  419,  420,  446,
      439,  448,  424,  426,  464,  465,  446,  438,  448,  407,
      481,  480,  479,  478,  477,  476,  475,  474,  409,  473,
      472,  471,  470,  469,  468,  467,  466,  459,  458,  457,
      456,  455,  454,  453,  452,  451,  450,  449,  462,  447,
      445,  463,  444,  443,  442,  441,  440,  437,  435,  464,
      465,  492,  434,  492,  492,  492,  492,  493,  493,  493,
      493,  494,  433,  494,  494,  494,  494,  495,  495,  496,
      496,  496,  496,  496,  496,  497,  432,  497,  497,  497,

      497,  498,  498,  498,  498,  498,  498,  499,  499,  499,
      431,  499,  499,  430,  429,  428,  427,  425,  423,  422,
      418,  412,  411,  410,  408,  398,  397,  393,  392,  391,
      389,  388,  386,  385,  384,  383,  382,  381,  378,  370,
      369,  364,  363,  359,  358,  357,  356,  354,  353,  352,
      349,  348,  346,  337,  327,  321,  320,  319,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  299,
      297,  284,  281,  274,  273,  272,  271,  269,  266,  265,
      264,  263,  262,  261,  259,  257,  256,  255,  248,  236,
      224,  223,  215,  202,  200,  198,  196,  195,  194,  193,

      192,  191,  190,  188,  184,  183,  181,  169,  149,  138,
      136,  129,  128,  127,  126,  125,  123,  122,  121,  120,
      119,  118,  116,  101,   95,   82,   75,   70,   69,   63,
       60,   59,   56,   55,   53,   50,   49,   47,   45,   31,
       23,   22,   21,   14,   12,   11,    7,    3,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "php.l"
#line 2 "php.l"
#include "wrap.h"
#line 837 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 21 "php.l"

#line 1057 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 491 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 949 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "php.l"
return COMENTARIO;
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 39 "php.l"
return COMENTARIO;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "php.l"
return RESERVADO;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "php.l"
return RESERVADO;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "php.l"
return RESERVADO;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "php.l"
return RESERVADO;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "php.l"
return RESERVADO;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "php.l"
return RESERVADO;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "php.l"
return RESERVADO;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "php.l"
return RESERVADO;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "php.l"
return RESERVADO;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "php.l"
return RESERVADO;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "php.l"
return RESERVADO;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "php.l"
return RESERVADO;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "php.l"
return RESERVADO;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "php.l"
return RESERVADO;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "php.l"
return RESERVADO;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "php.l"
return RESERVADO;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "php.l"
return RESERVADO;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "php.l"
return RESERVADO;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "php.l"
return RESERVADO;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "php.l"
return RESERVADO;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "php.l"
return RESERVADO;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "php.l"
return RESERVADO;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "php.l"
return RESERVADO;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "php.l"
return RESERVADO;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "php.l"
return RESERVADO;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "php.l"
return RESERVADO;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "php.l"
return RESERVADO;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "php.l"
return RESERVADO;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "php.l"
return RESERVADO;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "php.l"
return RESERVADO;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "php.l"
return RESERVADO;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "php.l"
return RESERVADO;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "php.l"
return RESERVADO;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "php.l"
return RESERVADO;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "php.l"
return RESERVADO;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "php.l"
return RESERVADO;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "php.l"
return RESERVADO;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "php.l"
return RESERVADO;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "php.l"
return RESERVADO;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "php.l"
return RESERVADO;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "php.l"
return RESERVADO;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 81 "php.l"
return RESERVADO;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "php.l"
return RESERVADO;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "php.l"
return RESERVADO;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 84 "php.l"
return RESERVADO;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "php.l"
return RESERVADO;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 86 "php.l"
return RESERVADO;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "php.l"
return RESERVADO;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "php.l"
return RESERVADO;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 89 "php.l"
return RESERVADO;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 90 "php.l"
return RESERVADO;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 91 "php.l"
return RESERVADO;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "php.l"
return VARIABLE;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 93 "php.l"
return OPERADOR;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 94 "php.l"
return OPERADOR;
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 95 "php.l"
return NWL;
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 96 "php.l"
return ESP;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 97 "php.l"
return CONTROL;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 98 "php.l"
return RESERVADO;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 99 "php.l"
return OPERADOR;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 100 "php.l"
return VALOR;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 101 "php.l"
return TEXTO;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 102 "php.l"
return ERROR;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 103 "php.l"
ECHO;
	YY_BREAK
#line 1527 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 491 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 491 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 490);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 103 "php.l"


int yywrap(void)
{
	return 1;
}

