
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[501] =
    {   0,
       76,   76,   86,   85,   77,   76,   85,   84,   85,   73,
       73,   85,   75,   73,   73,   73,   73,   73,   80,   75,
       73,   73,   73,   75,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   85,   77,   76,   73,    0,
       82,   84,   83,   72,   72,   72,   72,   72,   73,    0,
       82,   74,    0,   84,   80,    0,   17,   80,   80,    0,
       73,    2,   84,   84,   84,   22,   84,   84,   84,   84,
       84,   84,   79,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   78,   84,   84,   84,   84,

       84,   84,   73,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   82,   83,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
        0,   80,   80,    0,    0,    0,    0,   17,    0,   84,
       20,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   31,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   78,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   54,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   67,   84,   69,   70,   84,   84,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,

       72,   80,   18,    0,    0,    0,    0,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   32,
       33,   84,   84,   84,   84,   84,   84,   41,   42,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       53,   55,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   80,   84,   84,   84,   15,   16,   72,
        0,   72,   72,    9,   72,    5,   72,   72,   72,   72,
       72,    0,   18,    1,   84,   21,   84,   24,   25,   26,
       27,   84,   84,   84,   84,   84,   84,   34,   84,   84,
       38,   84,   84,   84,   44,   84,   84,   84,   84,   84,

       84,   84,   84,   52,   84,   57,   84,   84,   84,   84,
       84,   84,   84,   65,   66,   68,   71,    0,   72,    0,
       72,   72,   72,   72,    6,   72,   72,   72,   18,   84,
       84,   84,   84,   84,   30,   84,   84,   36,   84,   84,
       84,   84,   84,   84,   47,   84,   84,   84,   84,   84,
       84,   84,   84,   60,   84,   63,   64,    0,   72,    0,
       72,   72,    7,   72,   72,   72,   72,   84,   84,   84,
       28,   29,   84,   84,   84,   84,   43,   45,   84,   84,
       79,   84,   84,   84,   84,   58,   84,   61,    0,    0,
       72,   72,    0,   72,   11,   72,   72,    4,   72,   19,

       23,   84,   84,   84,   40,   46,   84,   84,   84,   84,
       84,   84,   84,   84,    0,    0,   72,   72,    0,   72,
        3,    8,   10,   84,   84,   39,   81,   84,   84,   84,
       50,   51,   84,   59,   84,    0,    0,   72,   72,    0,
       72,   35,   37,   81,   48,   84,   49,   84,   84,    0,
        0,   72,   72,    0,   72,   84,   56,   84,    0,    0,
       72,   72,    0,   72,   62,    0,    0,   72,   72,   13,
       13,    0,    0,   72,   72,    0,    0,   72,   72,    0,
        0,   72,   72,    0,    0,   72,   72,    0,    0,   72,
       72,   12,    0,   12,   72,    0,   72,   14,   14,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   34,
       50,   51,   52,   51,   53,   51,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   34,   54,   55,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[57] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    1,    1,
        1,    4,    1,    1,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    2,
        2,    2,    7,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[512] =
    {   0,
        0,    0,  985,  986,   55,   57,  962,   60,   99,  986,
      975,  973,  986,  959,  105,  104,  103,  111,  114,  986,
      118,  112,  958,  956,  121,  107,  126,  128,  133,  150,
      146,  956,  154,  123,  151,  116,  156,  115,  155,  168,
      165,  182,  183,  172,  184,  922,  151,  210,  954,  970,
        0,    0,    0,  932,    0,  929,  940,  189,  986,  962,
      961,  986,  208,  947,  205,  222,    0,  215,  223,  928,
      945,  986,  171,  200,  124,  944,  213,  208,  218,  224,
      226,  225,  943,  227,  228,  233,  236,  238,  239,  243,
      244,  245,  246,  247,  248,  942,  253,  254,  252,  256,

      255,  258,  941,  263,  267,  279,  266,  286,  282,  274,
      287,  291,  292,  295,  296,  297,  298,  957,    0,    0,
      930,  916,  919,  919,  919,  923,  294,  916,  925,  924,
      937,  933,  306,  328,  330,  335,  338,    0,  918,  304,
      927,  303,  331,  313,  333,  336,  321,  323,  335,  337,
      343,  926,  338,  345,  344,  353,  348,  347,  358,  349,
      360,  368,  367,  373,  371,  376,  379,  380,  382,  384,
      381,  925,  383,  404,  385,  386,  392,  164,  394,  396,
      398,  395,  399,  400,  924,  414,  923,  922,  405,  411,
      408,  903,  432,  903,  895,  904,  895,  899,  894,  895,

      248,  917,  443,  446,  922,  448,  893,  426,  422,  428,
      431,  444,  430,  416,  439,  445,  447,  448,  452,  910,
      470,  455,  457,  458,  459,  460,  462,  909,  908,  473,
      469,  465,  474,  466,  480,  484,  486,  487,  478,  492,
      907,  906,  493,  496,  497,  495,  499,  504,  503,  505,
      506,  507,  508,  905,  512,  513,  519,    0,    0,  538,
      897,  896,  889,    0,  894,    0,  896,  877,  875,  873,
      875,  532,  543,  986,  526,  895,  531,  894,  893,  892,
      891,  528,  536,  538,  539,  540,  541,  890,  542,  543,
      889,  548,  550,  554,  553,  557,  555,  558,  564,  565,

      568,  570,  574,  888,  576,  887,  575,  580,  581,  578,
      577,  587,  589,  886,  885,  884,  883,  862,  861,  860,
      859,  867,  856,  873,    0,  868,  867,  862,  882,  590,
      588,  591,  594,  596,  871,  600,  603,  604,  605,  606,
      607,  609,  612,  613,  870,  616,  619,  610,  625,  621,
      629,  632,  633,  869,  634,  868,  867,  635,  637,  846,
      845,  857,    0,  849,  841,  841,  843,  635,  643,  645,
      859,  858,  648,  653,  654,  658,  857,  856,  646,  647,
      677,  661,  664,  666,  667,  855,  669,  670,  829,  832,
      827,  830,  833,  832,    0,  827,  825,    0,  830,  845,

      844,  672,  673,  674,  843,  699,  675,  683,  685,  682,
      686,  687,  689,  694,  708,  823,  713,  822,  819,  814,
        0,    0,    0,  703,  704,  818,  725,  707,  709,  712,
      800,  789,  713,  783,  715,  764,  762,  760,  760,  761,
      760,  774,  773,  736,  771,  718,  770,  719,  721,  752,
      752,  750,  750,  744,  743,  722,  763,  727,  741,  740,
      739,  738,  749,  748,  756,  733,  747,  731,  745,  986,
        0,  741,  749,  750,  753,  745,  740,  743,  738,  744,
      739,  742,  736,  720,  738,  718,  735,  734,  631,  542,
      344,  986,  207,    0,  145,   80,   21,  986,    0,  986,

      801,  808,  812,  819,  821,  823,  830,  837,  844,  851,
      857
    } ;

static yyconst flex_int16_t yy_def[512] =
    {   0,
      500,    1,  500,  500,  500,  500,  500,  500,  501,  500,
      500,  502,  500,  500,  500,  500,  503,  500,  503,  500,
      500,  500,  500,  500,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  500,  500,  500,  500,  504,
        8,    8,  505,  506,  506,  506,  506,  506,  500,  502,
      502,  500,  500,  503,  503,  507,  508,  503,  503,  500,
      500,  500,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  504,  505,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      500,  500,  500,  507,  507,  507,  509,  508,  500,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  500,  507,  509,  510,  509,  500,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  506,  506,  506,
      500,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  510,  509,  500,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  500,  506,  500,
      506,  506,  506,  506,  506,  506,  506,  506,  510,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  500,  506,  500,
      506,  506,  506,  506,  506,  506,  506,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  500,  500,
      506,  506,  500,  506,  506,  506,  506,  506,  506,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  500,  500,  506,  506,  500,  506,
      506,  506,  506,  503,  503,  503,  511,  503,  503,  503,
      503,  503,  503,  503,  503,  500,  500,  506,  506,  500,
      506,  503,  503,  511,  503,  503,  503,  503,  503,  500,
      500,  506,  506,  500,  506,  503,  503,  503,  500,  500,
      506,  506,  500,  506,  503,  500,  500,  506,  506,  500,
      506,  500,  500,  506,  506,  500,  500,  506,  506,  500,
      500,  506,  506,  500,  500,  506,  506,  500,  500,  506,
      506,  500,  500,  506,  506,  500,  506,  500,  506,    0,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500
    } ;

static yyconst flex_uint16_t yy_nxt[1043] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   14,   15,   13,   16,   17,   18,   19,   13,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   32,   32,   34,   32,   35,   36,   37,
       32,   38,   39,   40,   41,   42,   43,   44,   45,   13,
        4,   13,   32,   13,   46,   13,   47,   47,   47,   48,
       50,   50,  499,   50,   51,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   52,   50,   52,   50,   50,
       50,   50,   50,   50,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   52,   52,   52,   52,   52,   52,   50,
       50,   50,   52,   50,   50,   50,   53,   62,   62,   63,
       65,  498,   66,   54,   59,   59,   59,   67,  500,   68,
       56,   69,   59,   71,   62,  500,  500,  500,   57,   59,
       59,   70,  500,  107,  500,  500,   73,  500,   77,  500,
       78,   58,   47,   47,  500,  100,   81,  103,   74,   84,
       82,   79,   75,   76,   80,  142,   83,  500,   85,   86,
       87,  500,  500,  497,   90,  500,  500,  500,   88,  101,
       89,   94,   91,   96,   95,  500,  500,  104,   92,  500,
       97,   98,  500,  500,   93,  102,   99,  105,  108,  110,

      106,  109,  112,  500,  500,  500,  114,  113,  248,  111,
      116,   47,   48,  140,  115,  124,  117,  125,  126,  127,
      131,  500,   65,  132,  135,  133,  500,  141,  128,  500,
      129,  130,   65,  136,  500,  496,  500,  137,   68,  500,
       69,  143,  147,  144,  500,  500,  500,  500,  500,  500,
      145,  146,  150,  152,  500,  151,  148,  500,  153,  500,
      500,  149,  157,  156,  500,  500,  500,  500,  500,  500,
      154,  158,  155,  500,  500,  500,  500,  500,  160,  500,
      167,  161,  159,  163,  500,  164,  162,  500,  500,  270,
      271,  165,  166,  173,  170,  500,  168,  169,  171,  175,

      500,  172,  174,  500,  177,  176,  178,  500,  500,  179,
      180,  183,  500,  500,  181,  182,  500,  500,  500,  500,
      187,  132,  197,  133,  500,  500,  190,  209,  189,  198,
      135,  184,  135,  186,  500,  185,  188,  135,  103,  136,
      205,  136,  500,  137,  500,  137,  136,  208,  211,  206,
      137,  203,  500,  137,  500,  210,  500,  500,  500,  500,
      214,   83,  212,  213,  500,  500,  500,  218,  500,  500,
      500,  495,  217,  221,  500,  219,  220,  215,  216,  500,
      223,  500,  224,  228,  232,  225,  230,  222,  500,  500,
      229,  231,  500,  234,  500,  226,  233,  500,  235,  227,

      500,  500,  500,  500,  500,  500,  500,  500,  243,   83,
      239,  236,  240,  500,  237,  500,  500,  500,  242,  500,
      500,  500,  244,  238,  241,  500,  500,  247,  254,  246,
      245,  253,  500,  252,  258,  500,  261,  500,  249,  250,
      256,  251,  255,  500,  280,  135,  257,  500,  205,  500,
      205,  500,  500,  259,  136,  277,  243,  206,  137,  206,
      500,  137,   83,  137,  273,  500,  500,  275,  500,  500,
      276,  283,  279,  500,  286,  278,  500,  282,  500,  500,
      500,  500,  281,  500,  262,  289,  500,  500,  291,  285,
      500,  500,  284,  293,  500,  500,  290,  254,  296,  500,

      295,  500,  287,  288,  298,  500,  292,  500,  500,  297,
      294,  301,  299,  500,  500,  302,  500,  500,  500,  303,
      500,  307,  286,  308,  500,  500,  500,  500,  500,  500,
      300,  309,  313,  500,  500,  304,  310,  312,  305,  306,
      500,   96,  318,  272,  311,  205,  317,  500,  329,  500,
      330,  315,  500,  314,  206,  316,  331,  500,  137,  500,
      500,  500,  500,  500,  500,  332,  494,  335,  337,  500,
       96,  500,  336,  334,  500,  500,  500,  333,  500,  500,
      339,  341,  340,  343,  338,  500,  500,  344,  342,  500,
      319,  500,  347,  345,  349,  500,  500,  500,  500,  500,

      346,  500,  500,  350,  351,  348,  353,  354,  500,  500,
      500,  500,  500,  356,   83,  500,  368,  500,  352,  355,
      357,  500,  371,  369,  500,  500,  500,  500,  500,   96,
      500,  500,  374,  500,  500,  370,  382,  500,  373,  372,
      500,  376,  500,   96,  380,  384,  500,  381,  375,  377,
      500,  379,  383,  500,  500,  500,  500,  378,  493,  389,
      386,  391,  388,  390,  500,  392,  500,  500,  500,  500,
      385,  401,  402,   83,  500,  500,  387,  403,  400,  500,
      404,  408,  500,  406,  407,  500,  405,  500,  500,  409,
      500,  500,  411,  500,  500,  500,  500,  413,  500,  425,

      427,  427,  410,  500,  500,  426,  500,  500,  500,  412,
      500,  431,  436,  424,  432,  500,  434,  436,  428,  433,
      500,  429,  414,  430,  500,  500,  427,  427,  500,  408,
      500,  442,  435,  500,  500,  443,  500,  500,  500,  500,
      500,  447,  500,  500,  456,  476,  446,  458,  500,  445,
       83,  448,  449,  477,  476,  465,  457,  477,  492,  491,
      436,  490,  489,  488,  487,  438,  486,  485,  484,  483,
      482,  481,  480,  475,  474,  473,  472,  500,  471,  470,
      469,  468,  467,  466,  500,  464,  463,  462,  461,  460,
      459,  500,  500,  476,  500,  500,  455,  454,  453,  452,

      451,  477,  478,  450,  500,  479,   55,   55,   60,   60,
      500,   60,   60,   60,   60,   64,   64,   64,   64,   50,
       50,  500,   50,   50,   50,   50,  119,  119,  120,  120,
      134,  134,  134,  134,  134,  134,  134,  138,  138,  500,
      138,  138,  138,  138,  204,  204,  204,  204,  204,  204,
      204,  205,  205,  205,  205,  441,  205,  205,  444,  444,
      440,  439,  437,  444,  500,  500,  500,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  500,  500,  500,  500,
      500,  399,  398,  397,  396,  395,  394,  393,  500,  500,
      500,  500,  500,  272,  367,  366,  365,  364,  363,  362,

      361,  360,  359,  358,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  500,  500,  500,  500,
      500,  500,  274,  272,  202,  269,  268,  267,  266,  265,
      264,  263,  260,  500,  500,  500,  500,  500,  500,  207,
      202,   63,  201,  200,  199,  196,  195,  194,  193,  192,
      191,  118,  500,  500,  500,  500,   59,  139,  500,   61,
       61,  123,  122,  121,  118,   59,   59,  500,   72,   59,
       59,   61,   59,   49,  500,    3,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500
    } ;

static yyconst flex_int16_t yy_chk[1043] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    6,    6,
        8,    8,  497,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    9,   15,   16,   15,
       17,  496,   18,    9,   17,   16,   15,   18,   26,   19,
        9,   19,   18,   22,   22,   19,   38,   36,    9,   21,
       21,   21,   25,   38,   34,   75,   25,   27,   26,   28,
       27,    9,   47,   47,   29,   34,   28,   36,   25,   29,
       28,   27,   25,   25,   27,   75,   28,   31,   29,   29,
       29,   30,   35,  495,   30,   33,   39,   37,   29,   35,
       29,   31,   30,   33,   31,  178,   41,   37,   30,   40,
       33,   33,   73,   44,   30,   35,   33,   37,   39,   40,

       37,   39,   41,   42,   43,   45,   42,   41,  178,   40,
       44,   48,   48,   73,   43,   58,   45,   58,   58,   58,
       63,   74,   65,   63,   66,   63,   65,   74,   58,   78,
       58,   58,   68,   66,   77,  493,   68,   66,   69,   79,
       69,   77,   79,   78,   69,   80,   82,   81,   84,   85,
       78,   78,   81,   82,   86,   81,   79,   87,   84,   88,
       89,   80,   88,   87,   90,   91,   92,   93,   94,   95,
       85,   89,   86,   99,   97,   98,  101,  100,   90,  102,
       98,   91,   89,   93,  104,   94,   92,  107,  105,  201,
      201,   95,   97,  102,   99,  110,   98,   98,  100,  105,

      106,  101,  104,  109,  106,  105,  107,  108,  111,  107,
      108,  111,  112,  113,  109,  110,  114,  115,  116,  117,
      113,  133,  127,  133,  142,  140,  117,  142,  115,  127,
      134,  111,  135,  112,  144,  111,  114,  136,  116,  134,
      137,  135,  147,  134,  148,  135,  136,  140,  144,  137,
      136,  136,  143,  137,  145,  143,  149,  146,  150,  153,
      148,  145,  146,  147,  151,  155,  154,  151,  158,  157,
      160,  491,  150,  154,  156,  151,  153,  149,  149,  159,
      156,  161,  156,  157,  161,  156,  159,  155,  163,  162,
      158,  160,  165,  163,  164,  156,  162,  166,  164,  156,

      167,  168,  171,  169,  173,  170,  175,  176,  174,  165,
      169,  166,  170,  177,  167,  179,  182,  180,  173,  181,
      183,  184,  175,  168,  171,  174,  189,  177,  184,  176,
      175,  183,  190,  182,  191,  186,  193,  214,  179,  180,
      189,  181,  186,  209,  214,  203,  190,  208,  204,  210,
      206,  213,  211,  191,  203,  211,  174,  204,  203,  206,
      215,  204,  210,  206,  206,  212,  216,  208,  217,  218,
      209,  217,  213,  219,  221,  212,  222,  216,  223,  224,
      225,  226,  215,  227,  193,  223,  232,  234,  225,  219,
      231,  221,  218,  227,  230,  233,  224,  231,  233,  239,

      232,  235,  221,  222,  235,  236,  226,  237,  238,  234,
      230,  238,  236,  240,  243,  238,  246,  244,  245,  239,
      247,  245,  221,  246,  249,  248,  250,  251,  252,  253,
      237,  247,  251,  255,  256,  240,  248,  250,  243,  244,
      257,  256,  260,  272,  249,  273,  257,  275,  272,  282,
      275,  253,  277,  252,  273,  255,  277,  283,  273,  284,
      285,  286,  287,  289,  290,  282,  490,  285,  289,  292,
      287,  293,  286,  284,  295,  294,  297,  283,  296,  298,
      292,  294,  293,  296,  290,  299,  300,  297,  295,  301,
      260,  302,  300,  298,  302,  303,  307,  305,  311,  310,

      299,  308,  309,  303,  305,  301,  308,  309,  312,  331,
      313,  330,  332,  312,  311,  333,  330,  334,  307,  310,
      313,  336,  333,  331,  337,  338,  339,  340,  341,  336,
      342,  348,  338,  343,  344,  332,  348,  346,  337,  334,
      347,  340,  350,  343,  346,  350,  349,  347,  339,  341,
      351,  344,  349,  352,  353,  355,  368,  342,  489,  358,
      352,  359,  355,  358,  369,  359,  370,  379,  380,  373,
      351,  369,  373,  370,  374,  375,  353,  374,  368,  376,
      375,  381,  382,  379,  380,  383,  376,  384,  385,  382,
      387,  388,  384,  402,  403,  404,  407,  387,  381,  403,

      406,  406,  383,  410,  408,  404,  409,  411,  412,  385,
      413,  410,  415,  402,  411,  414,  413,  417,  407,  412,
      406,  408,  388,  409,  424,  425,  427,  427,  428,  381,
      429,  424,  414,  430,  433,  425,  435,  444,  444,  446,
      448,  430,  449,  456,  446,  472,  429,  449,  458,  428,
      456,  433,  435,  473,  474,  458,  448,  475,  488,  487,
      415,  486,  485,  484,  483,  417,  482,  481,  480,  479,
      478,  477,  476,  469,  468,  467,  466,  465,  464,  463,
      462,  461,  460,  459,  457,  455,  454,  453,  452,  451,
      450,  447,  445,  472,  443,  442,  441,  440,  439,  438,

      437,  473,  474,  436,  434,  475,  501,  501,  502,  502,
      432,  502,  502,  502,  502,  503,  503,  503,  503,  504,
      504,  431,  504,  504,  504,  504,  505,  505,  506,  506,
      507,  507,  507,  507,  507,  507,  507,  508,  508,  426,
      508,  508,  508,  508,  509,  509,  509,  509,  509,  509,
      509,  510,  510,  510,  510,  420,  510,  510,  511,  511,
      419,  418,  416,  511,  405,  401,  400,  399,  397,  396,
      394,  393,  392,  391,  390,  389,  386,  378,  377,  372,
      371,  367,  366,  365,  364,  362,  361,  360,  357,  356,
      354,  345,  335,  329,  328,  327,  326,  324,  323,  322,

      321,  320,  319,  318,  317,  316,  315,  314,  306,  304,
      291,  288,  281,  280,  279,  278,  276,  271,  270,  269,
      268,  267,  265,  263,  262,  261,  254,  242,  241,  229,
      228,  220,  207,  205,  202,  200,  199,  198,  197,  196,
      195,  194,  192,  188,  187,  185,  172,  152,  141,  139,
      132,  131,  130,  129,  128,  126,  125,  124,  123,  122,
      121,  118,  103,   96,   83,   76,   71,   70,   64,   61,
       60,   57,   56,   54,   50,   49,   46,   32,   24,   23,
       14,   12,   11,    7,    3,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,

      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  500,  500,  500,  500,  500,  500,
      500,  500
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "php.l"
#line 2 "php.l"
#include "wrap.h"
#line 851 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 21 "php.l"

#line 1071 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 501 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 986 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "php.l"
return PREDETERMINADO;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "php.l"
return IDENTIFICADOR;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "php.l"
return COMENTARIO;
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 39 "php.l"
return COMENTARIO;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "php.l"
return RESERVADO;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "php.l"
return RESERVADO;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "php.l"
return RESERVADO;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "php.l"
return RESERVADO;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "php.l"
return RESERVADO;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "php.l"
return RESERVADO;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "php.l"
return RESERVADO;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "php.l"
return RESERVADO;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "php.l"
return RESERVADO;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "php.l"
return RESERVADO;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "php.l"
return RESERVADO;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "php.l"
return RESERVADO;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "php.l"
return RESERVADO;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "php.l"
return RESERVADO;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "php.l"
return RESERVADO;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "php.l"
return RESERVADO;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "php.l"
return RESERVADO;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "php.l"
return RESERVADO;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "php.l"
return RESERVADO;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "php.l"
return RESERVADO;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "php.l"
return RESERVADO;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "php.l"
return RESERVADO;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "php.l"
return RESERVADO;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "php.l"
return RESERVADO;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "php.l"
return RESERVADO;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "php.l"
return RESERVADO;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "php.l"
return RESERVADO;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "php.l"
return RESERVADO;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "php.l"
return RESERVADO;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "php.l"
return RESERVADO;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "php.l"
return RESERVADO;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "php.l"
return RESERVADO;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "php.l"
return RESERVADO;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "php.l"
return RESERVADO;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "php.l"
return RESERVADO;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "php.l"
return RESERVADO;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "php.l"
return RESERVADO;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "php.l"
return RESERVADO;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "php.l"
return RESERVADO;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "php.l"
return RESERVADO;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "php.l"
return RESERVADO;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 81 "php.l"
return RESERVADO;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "php.l"
return RESERVADO;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "php.l"
return RESERVADO;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 84 "php.l"
return RESERVADO;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "php.l"
return RESERVADO;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 86 "php.l"
return RESERVADO;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "php.l"
return RESERVADO;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "php.l"
return RESERVADO;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 89 "php.l"
return RESERVADO;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 90 "php.l"
return RESERVADO;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 91 "php.l"
return RESERVADO;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "php.l"
return RESERVADO;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 93 "php.l"
return VARIABLE;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 94 "php.l"
return OPERADOR;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 95 "php.l"
return OPERADOR;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 96 "php.l"
return OPERADOR;
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 97 "php.l"
return NWL;
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 98 "php.l"
return ESP;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 99 "php.l"
return CONTROL;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 100 "php.l"
return RESERVADO;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 101 "php.l"
return VALOR;
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 102 "php.l"
return CONTROL;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 103 "php.l"
return TEXTO;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 104 "php.l"
return ERROR;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 105 "php.l"
return ERROR;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 106 "php.l"
ECHO;
	YY_BREAK
#line 1557 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 501 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 501 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 500);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 106 "php.l"


int yywrap(void)
{
	return 1;
}

